# Generated by Django 4.2.4 on 2023-08-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='in_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='not_done',
            field=models.BooleanField(default=False),
        ),
    ]
